### ISSUE TITLE
Not Available via Bower

### ISSUE THREAD

**Issue by nkoterba** [maybenull/angular-authz#6]
I noticed you have a `bower.json` file in the repo.

Is `angular-authz` available via bower?  When I run `bower install angular-authz` I get:

``` javascript
$ bower install angular-authz
bower                        ENOTFOUND Package angular-authz not found
```

**Comment by maybenull** [comment]
Crap.  No.   Thx. Will fix within 24hrs

**Comment by nkoterba** [comment]
@maybenull Thanks for the quick turnaround. I've been able to get things to work just referencing the source but being able to use `bower` would be great.

Availability via NPM would be even better :-)

If I do a pull request to implement this capability are you ok maintaining it?

**Comment by nkoterba** [comment]
@maybenull: Any update on the availability of this package via bower?

**Comment by maybenull** [comment]
I didn't quite hit the 24hr mark.  but resolved.
